# Numerik Blatt 01

___________________

#### Von
* Ege Cabuk

#### b)
   $b_i = Ax = \sum_{j=1}^{n}x_j a_j$

#### c)

In [ ]:
#Das ist ein Kommentar in Python!

#### d)

In [31]:
import numpy as np

array1 = [1, 2, 3, 4]

vektor1 = np.array(array1)
  
print("1 x 4 Zeilen Vektor: ", vektor1)

1 x 4 ZeilenVektor:  [1 2 3 4]


#### e)

In [32]:
import numpy as np

array2 = [[1],
           [2],
           [3],
           [4],
           [5]]

vektor2 = np.array(array2)
  
print("5 x 1 Zeilen Vektor: ", vektor2)

5 x 1 ZeilenVektor:  [[1]
 [2]
 [3]
 [4]
 [5]]


#### f)

In [26]:
import numpy as np

matrix_3d = np.zeros((3,3))
print(matrix_3d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### g)

In [27]:
import numpy as np

matrix = np.zeros((4,3))
print(matrix[1])

[0. 0. 0.]


#### h)

In [28]:
import numpy as np

matrix = np.zeros((4,4))
print(matrix[2])

[0. 0. 0. 0.]


#### i)

In [34]:
import numpy as np

matrix = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
print(matrix.transpose())

[[21 11 43]
 [22 22 77]
 [23 33 89]]


#### j

In [38]:
import numpy as np

matrix1 = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
matrix2 = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
print(matrix1 * matrix2)
print(np.matmul(matrix1, matrix2))

[[ 441  484  529]
 [ 121  484 1089]
 [1849 5929 7921]]
[[ 1672  2717  3256]
 [ 1892  3267  3916]
 [ 5577  9493 11451]]


#### k)

In [54]:
import numpy as np

matrix1 = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
matrix2 = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))
matrix3_c = np.c_[matrix2, matrix1]
matrix4_r = np.r_[matrix3, matrix3]
print("Spalten hinzugefügt: ")
print(matrix3_c)
print("_________________________________________________")
print("Zeilen hinzugefügt: ")
print(matrix4_r)

Spalten hinzugefügt: 
[[21 22 23 21 22 23]
 [11 22 33 11 22 33]
 [43 77 89 43 77 89]]
_________________________________________________
Zeilen hinzugefügt: 
[[21 22 23 21 22 23]
 [11 22 33 11 22 33]
 [43 77 89 43 77 89]
 [21 22 23 21 22 23]
 [11 22 33 11 22 33]
 [43 77 89 43 77 89]]


#### l)

In [52]:
import numpy as np

matrix1 = np.array(([21, 22, 23], [11, 22, 33], [43, 77, 89]))

print(matrix1.shape)

(3, 3)


#### m)

In [61]:
import numpy as np

matrix1 = np.array(([11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33]))

print(matrix1.reshape(14,4))

[[11 22 33 43]
 [77 89 33 11]
 [22 33 43 77]
 [89 33 11 22]
 [33 43 77 89]
 [33 11 22 33]
 [43 77 89 33]
 [11 22 33 43]
 [77 89 33 11]
 [22 33 43 77]
 [89 33 11 22]
 [33 43 77 89]
 [33 11 22 33]
 [43 77 89 33]]


#### n)

In [69]:
import numpy as np

vektor1 = np.array([[1],
           [2],
           [3]])
vektor2= np.array([[1],
           [2],
           [3]])
for i in range(9999):
     vektor1 = np.c_[vektor1, vektor2]
    
print(vektor1)

[[1 1 1 ... 1 1 1]
 [2 2 2 ... 2 2 2]
 [3 3 3 ... 3 3 3]]


#### o)

In [77]:
import numpy as np

matrix1 = np.array(([-11, 22, 33, 43, 77, -89, 33],
                   [11, 22, 33, -43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, -22, 33, 43, -77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, 22, 33, 43, 77, 89, 33],
                   [11, -22, 33, -43, 77, 89, 33]))

for i in range(8):
    for j in range(7):
         if(matrix1[i][j]<0):
                matrix1[i][j] = 0
                
print(matrix1)
                

[[ 0 22 33 43 77  0 33]
 [11 22 33  0 77 89 33]
 [11 22 33 43 77 89 33]
 [11 22 33 43 77 89 33]
 [11  0 33 43  0 89 33]
 [11 22 33 43 77 89 33]
 [11 22 33 43 77 89 33]
 [11  0 33  0 77 89 33]]


#### p)

In [127]:
import numpy as np

matrix1 = np.array([[0]])
j = 0

for i in range(100):
    if(i == 0):
        if(matrix1[0] == 0):
            matrix1[0] = 7
    if(i > 0):
        j += 1
        if(j == 7):
            j = 0;
            if(i != 7):
                matrix1 = np.r_[matrix1, [[i]]]
            
        
    

                

print(matrix1)
                

[[ 7]
 [14]
 [21]
 [28]
 [35]
 [42]
 [49]
 [56]
 [63]
 [70]
 [77]
 [84]
 [91]
 [98]]


#### q)

In [168]:
import numpy as np

matrix1 = np.array([[0]])
j = 0

for i in range(100):
     matrix1 = np.r_[matrix1, [[i]]]

for i in range(100):
    if(i == 0):
        matrix1[i][0] = i
    # Modulo 2 = 1 weil bei null beginnend
    if(i%2 == 1):
        matrix1[i][0] = 0
                
print(matrix1)

[[ 0]
 [ 0]
 [ 1]
 [ 0]
 [ 3]
 [ 0]
 [ 5]
 [ 0]
 [ 7]
 [ 0]
 [ 9]
 [ 0]
 [11]
 [ 0]
 [13]
 [ 0]
 [15]
 [ 0]
 [17]
 [ 0]
 [19]
 [ 0]
 [21]
 [ 0]
 [23]
 [ 0]
 [25]
 [ 0]
 [27]
 [ 0]
 [29]
 [ 0]
 [31]
 [ 0]
 [33]
 [ 0]
 [35]
 [ 0]
 [37]
 [ 0]
 [39]
 [ 0]
 [41]
 [ 0]
 [43]
 [ 0]
 [45]
 [ 0]
 [47]
 [ 0]
 [49]
 [ 0]
 [51]
 [ 0]
 [53]
 [ 0]
 [55]
 [ 0]
 [57]
 [ 0]
 [59]
 [ 0]
 [61]
 [ 0]
 [63]
 [ 0]
 [65]
 [ 0]
 [67]
 [ 0]
 [69]
 [ 0]
 [71]
 [ 0]
 [73]
 [ 0]
 [75]
 [ 0]
 [77]
 [ 0]
 [79]
 [ 0]
 [81]
 [ 0]
 [83]
 [ 0]
 [85]
 [ 0]
 [87]
 [ 0]
 [89]
 [ 0]
 [91]
 [ 0]
 [93]
 [ 0]
 [95]
 [ 0]
 [97]
 [ 0]
 [99]]


#### r)

In [177]:
import numpy as np

matrix1 = np.array([[0]])

for i in range(100):
    if(i!=0):
        matrix1 = np.r_[matrix1, [[i]]]

j = 1;
for i in range(101):
    if(j == 0):
        matrix1[j][0] = j
    if(i%2 == 0 and i!= 0):
        matrix1 = np.delete(matrix1, j, axis=0)
        j += 1
        
                
print(matrix1)

[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]
 [20]
 [22]
 [24]
 [26]
 [28]
 [30]
 [32]
 [34]
 [36]
 [38]
 [40]
 [42]
 [44]
 [46]
 [48]
 [50]
 [52]
 [54]
 [56]
 [58]
 [60]
 [62]
 [64]
 [66]
 [68]
 [70]
 [72]
 [74]
 [76]
 [78]
 [80]
 [82]
 [84]
 [86]
 [88]
 [90]
 [92]
 [94]
 [96]
 [98]]


#### s)

In [178]:
import numpy as np

print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### t)

In [184]:
import numpy as np

matrix1 = np.array(([-11, 22, 33, 43, 77],
                   [11, 22, 33, -43, 77],
                   [11, 22, 33, 43, 77],
                   [11, 22, 33, 43, 77],
                   [11, -22, 33, 43, -77]))
for i in range(5):
    print(matrix1[i][i])
    
np.diag(matrix1)

-11
22
33
43
-77


array([-11,  22,  33,  43, -77])

#### u)

#### v)